keys:
  - &user_sdk age1x7nsts9n0us99z7v2d5wqteqvt8was8ghxjnfmrg29q2vdhkqq2s3553u8
  - &user_sysadmin age1uuc2fefygw9ffkd3zeye9a98lu7srftr7ryaz5wtp4uzmczas37st4rp5u
  - &user_nixos age1gk8pnzm29uas2wsw5v5fjmlxxn6txv6gg5ad8yy7tvatlhgfw9rqyjrg0g
  - &machine_babs age1m3h9cfyuqdapfuw3dydx90qwcdpmtqts9yxp7gljd808595fzdxs0ea4t8
  - &machine_furrball age1jyrcctsjpxqd732emuhuyrp2nn3f8ejzxmanyt9pgwyzs46kgaesd08muf
  - &machine_thebrain age1kwrx24t8lagyk28lvv5tx9v0aun764f4pc72kcnyk2nw5rjjvghqhj8gqv

creation_rules:
  - path_regex: secret/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_sdk
          - *user_sysadmin
          - *user_nixos
          - *machine_babs
          - *machine_furrball
          - *machine_thebrain
