service:
    gitea:
        root_password: ENC[AES256_GCM,data:gxeYMukDBgZBzIEXiBZYaw==,iv:RrKxGOQyjxOO9uk5bn8UZFXTEWbeCA6Wnu4d4zmFf44=,tag:1yfKw1Zr/AcCzG89LVK6Pg==,type:str]
        db_password: ENC[AES256_GCM,data:lsacNiPIM8QGWxIcyZZC5A==,iv:V4GBelZlARfm1QUR7+84uIvs8bOEiB6Qkws5sykxsV0=,tag:PWJuOLWMb7f5rN7ORlDFLA==,type:str]
    wireguard:
        server:
            private_key: ENC[AES256_GCM,data:ghFn846MB5valkixrvWRbPiGzPkr+u9/RgqFRcrIOgC5FXozz4SDS6PiYcY=,iv:LN4t1TtODKG8t/uV9Hz4eQZWT8GgrsDDsqG4EdEFf3c=,tag:LRTK4kkna2SD89xtUqzioA==,type:str]
            public_key: ENC[AES256_GCM,data:5GhZJKl1xiAC8z5iG/fjz3x0OQnLB2boDvO7YqQVf5S8bnw424DEb0vCA/A=,iv:EBHLqwuIQNrLIRVVJcTrQmlR8WMDl56CT/iowYejAnY=,tag:p1OlT+w1m8Tpm04OT3MHAw==,type:str]
        peers:
            buster:
                private_key: ENC[AES256_GCM,data:iJfOonJDV9V4Ni7zjwjGTT/ot7ix8R5PfggelB663oQ7IhbYl0ysyOhgalg=,iv:xVL+RxLTCQAYteScMD/VdvxDtv5+HSUVo/mpeIMgnfE=,tag:jwZkEHgtyZsOf6EF6ol6nw==,type:str]
                public_key: ENC[AES256_GCM,data:Vv+bvshUzsHIJUYmRsg+btj7bDapa2575skQYK3GZSDBDO0D5wqOJZdikKI=,iv:75G+TpX+cBl86ikrB7YmetSH/X83EBDY6opv/jySlb8=,tag:LgS1S+l6DnYkVexIrujLwg==,type:str]
    acme:
        cloudflare_sffjunkie_dns_api_token: ENC[AES256_GCM,data:uqx10kCOrWcuzsFx54ipFLkfDSBxojy2HARJw1re0kOZX1jGNPSUdQ==,iv:c4yu4NyJGkymdiXlnCQJq6ltAIjM8m8JJ9t8ZdqGL7o=,tag:FSC3zHZWcsPvZmlES2WUwA==,type:str]
        cloudflare_sffjunkie_zone_id: ENC[AES256_GCM,data:wUFO4Qzgh3PSISOd1lSETrEN23GhoKdIr8lzphuFV5Y=,iv:2Gj3EKcHk0OsbQ+lDzOkVEzTw/bP8h18TSYCyceOcKc=,tag:OYioa22sB7Bzg34u01gdrw==,type:str]
        cloudflare_looniversity_dns_api_token: ENC[AES256_GCM,data:aXqv1PMEorPXRARNKr8lepiBdU3bupai9+Hpo+ninwYxwRh+U8Vs2g==,iv:Wxc6ghmtQib+OF0g3Ei1/yKXAeZHV+c7JpO9YnHKYHo=,tag:aQNdL+drSKeDhc2UUapcNw==,type:str]
        cloudflare_looniversity_zone_id: ENC[AES256_GCM,data:Rtj4RA50POBK84c/A2BXg4qHdz5H3XAqujd6Jbls40k=,iv:tMLj4QA+VG9JZsKjcua+nla4LdyuN8y/ngvRXFNukLY=,tag:1n9hhZX7T1RavfeUlSAPlg==,type:str]
        cloudflare_account_id: ENC[AES256_GCM,data:Jp9mNGjVwAJzlHy0dNlvuf+3DpV6G0p/oy8CiqjT1xE=,iv:rN9tixQe5b2mwo/v+E1WjUy5REP2EYBw4KAcBsJtivw=,tag:tCW04/0vUeAt64BQ8FQepQ==,type:str]
        cloudflare_api_key: ENC[AES256_GCM,data:mfUf+4IOX0AYrSiw7SKcKpj1QSpHbMdhsA58lubrYf85M5Jh/g==,iv:1l2mJAFIbNNl9I0jM3vXDdLSPXeq0tgKz6qYgOhT4+g=,tag://3Hmp7ZXdmoq/o6XZEXnA==,type:str]
    graylog:
        password_secret: ENC[AES256_GCM,data:0CdaSw+JXVp1U72TOgjCYZr8g1w77qhgNPBLetJipMqkT0DlZ4VHQ0otZxhgB9XFEyUaNk/aRmVeSX+W0wVmDeZd1UKyJFFEMNeVg0qQTFT2ptCKAf7jkhISLUhC6l5b,iv:1SBr5YyEyfaKd1dKgyuudNCwsejqXKcxTvSTPaX8wUI=,tag:pr0Lj+xzTB42aX7VELJb0Q==,type:str]
        root_user_name: ENC[AES256_GCM,data:N0QFNt0=,iv:1b98kPPpVVKisq9GXO1ieejN33No/Xf+OTv6vO+EzhQ=,tag:0WmusAfooe7jxZ8NkY7t+Q==,type:str]
        root_password_hash: ENC[AES256_GCM,data:PatL4NiZwl+KF3vwctIexrgtH+iGHLyUfmOY9ndO+RxLqNfu3xpYgGzwsWV3Jnnn7ce2mgMbDZoRYXpCpwqxag==,iv:Yc1T0jP5orTTIAJI5Ty1LEpgkif+a+Y56CJZxtJdvM8=,tag:NOucoGumzTN+wXgHzvfvHg==,type:str]
    lldap:
        jwt: ENC[AES256_GCM,data:yPGVqKSHXLipW4a2p1hS3BF7fsE2/RF68vy+YCTvmbc=,iv:Z2PdpAZ/na3oZn/sQUWCfiiJYlEuCE6ahgUHdKoIgOs=,tag:wrEXiF9g6DCGPWyVi0pZKQ==,type:str]
        key_seed: ENC[AES256_GCM,data:2H64le9zWZ3Wps9G8aitCcKsle9S1sBadsN2BzZ+EV0=,iv:ywQeIsm1IingEXZbnitjucSGSVxx71MF+u202b06jRM=,tag:YbLgJ8laFMvZVShvsCII1A==,type:str]
        admin_password: ENC[AES256_GCM,data:qlZE27s65FInHuuyfcBB/A==,iv:FvQ88EuvivISh4cpFjBiw4NGGfNEJP42IddmijjxIho=,tag:a3ycHmZpr8jaa5EgZ3hVqQ==,type:str]
    nextcloud:
        admin_password: ENC[AES256_GCM,data:5r1i3Pw275oQ7zvDHAWsQekEac0=,iv:wC8ySDljXlQwADYXVjY5pYXXDrNzupM8sh7UpZ6RmI8=,tag:0QpvG827WKfMs5cu8t5eZw==,type:str]
        db_password: ENC[AES256_GCM,data:2wKXyaFiWHP5VDou5FA1dw==,iv:Wm8leBV5PORXZRAtGTAYiCdlKUPmbzGI0JUEcHhqq3U=,tag:83mQv9mpQLZyrCP2oFBlWQ==,type:str]
    step_ca:
        intermediate_password: ENC[AES256_GCM,data:hg==,iv:hIVw1PsyL2ykyH1IRuIQwRwzDkMqYADNHGVa65zlc94=,tag:MnNcqSXUij6o+XZvsfTscA==,type:str]
        root_ca_crt: ENC[AES256_GCM,data:FA==,iv:BwYu2VyZi+88E8+gZZcwKASUaAXvUhDSgkF6XtfminQ=,tag:dZ5Zqcn0JF0Ynhdyxy44QA==,type:str]
        intermediate_ca_crt: ENC[AES256_GCM,data:Ag==,iv:z0z/tUP5x6GBEiB86ppd5wNATMz7TEcukO68MHyOGyQ=,tag:L23SOJ2GFcpwzPdeTvmogw==,type:str]
        intermediate_ca_key: ENC[AES256_GCM,data:JQ==,iv:pcYRNCdjAPZxm9T+Bw035iBv25zh9BnsUwW0dG5KDW0=,tag:hX7g15zl0vmOtPMZuoqmMw==,type:str]
    minio:
        root_user: ENC[AES256_GCM,data:Q+4qk4Q=,iv:hoTP7RALIs42K7ObeOivDMkfvfWxcWkWW+6SWdscRgo=,tag:VZKT/V5v6Ku3oA1eHTx1lg==,type:str]
        root_password: ENC[AES256_GCM,data:VOscnsUNSq6sTPyUK1Ei35FPF5Q=,iv:U5GPb0loEqVi+sn7wk44ZpzkxJtEanpfKH2Fb168IlI=,tag:+Tj/bb6GoeI0Va5zn+yiiA==,type:str]
    rclone:
        ini: ENC[AES256_GCM,data:bISL2+R0GUdkFbRuL+lkVZml3zbrS6FF50lTNn+WQZsB838/SW6Nm9ZkjjlpUbR4o2Pg0h4U9dP1Q3XlL8JHgg4CDfFvGX9vHDb1SWVX1HJwRAeHEydoeO71rbbgxJ0m3XWwtNCM9UILYwaZKQMaDGR1/qs3iRYNK4q5AD1ll6gQeLlRMOf8iVoApI6mT5Ug9DtxiKZMe5NcuVhY2oX55rh9OVi9wrfNXhhT4+k2qAH9XDDcFLuxH9MjXjoOD1xpn8HXAIvZM/GMEPq34mgZtk+I8gW2pDekhhGZcmKqgOj18usrAsTXK8nY/xWoGXr0b2yLw6ZPvbL+LM7H4mOJ0nxBrThJTK+N+wSVHoOzkQlyTS16s0RSTfyNUrBPWqIFDUWWfd4ZLY8SftZLxJu0e1W6ilw/kF2ljvvgRwFh1KxPfu8XIRMkO5c/UzxLHkBZybKyQ+EvBMWmUKSInPudsrsrAd2SNsDbgIr9lqhL6OMWLPRSwT12y6RRG+pvGpnNTU5qDaLou4fsHxdpgxJvlRhKDTKTmNVnNJUu+tQkRqRWtWABpBHDBlRvPnsnR36YMeeC9/0uoJbtS/UIl8hje1Vczf3/2X6+n1jP+veevRRfGhVtsXcnG4Nz/per5l8QBjPsOC6tnbydEGQqAFNNxc2iILWXpTrAanFeMKIRsBMPFDx7Q+VvuA5VfHcMZo8aYWIBpwOuV7P1G0uvh/XZwVfQPLOLNFR+YJ8uhT6hGht5a9HDNFXFDI8VtBFUQmaO6MWjcTT6yg1f18mz3CP7NP3U6HK1mcoqsRLQUKXw/7xoGNIAXKbI18anYS1nY6qGugdBeMWpvfvEd7qeJbAQzrj64k1KYcbfWn0w0FOiFbCNp9n/A4pA4t4l2lUNZC7CUgChb3NCKhmxeUs+tSQkXvt8/bG9pWLtn3iLAqMMrmk5le4FYH6bDLfHnnP+xxR5Yhn4inQCL6u/1aUxhI8b8bD7N3vQ2A0rxoAZ0QuvtDX8WsYqkyC3CWMWESU10iNeuN4uyRv9UOP/nayr08MIgzbXETzW6OCvas2iZFUlcBl45wSPNpwSvd2IT8vmlQYpdeD8b7DoIWosAy1O89fgYRkEnfZiuSUS5QYkOtkUUhIsaXDNTF+Icm2XvTxWVwYZebLRA4xHhZX+Y1MRx7nLtq2Y4vVzj7GP84ciwKvCiyFqcQ6TRmnbk5g+9JhnZcOHlvX9ERB6Bhz4ASYBE6ee/URBmsqG3BYG1cPLY8wvdlrWBdnfz5ShoymzVtZKL00ihO0/tLmfefm0HV7/c0xXauMoMTFyauwo8KWsfG17s14N5dYzLtI7qTo9PUBluJGVY/RMaUi5dLGCY/KY2oOckqoLm38ZuqAc7ya8lq4F1r6LzYGCrQtfuotwCFccv/Dxg6tIFAhj68p7jCtRL6QdVbnXHxWUMPE+BgWccG+p9ESEoGxHE8CRRH9kAtlwMN6rFJEI49C6GvZa9aVZZ4/uMhTMbQoWE1cpoMtRM5RtE+FScFdw2DbtSBg427Xyte73Uusn4btt5FLOGI2XKm/FiVEV7ZLcF0i4DlHlst0ZxoCVcUSJn7zTJLEn+rvVzXSzbtqAG4Qax1q8+lMGSvKy5DuBDJCviHQ4Lfijt5+yUvp8dpwRBEv9FRA7NJwhC5a73cGlGf4Jclvu9NDHXJZjT/cf58XnwDoP4W6v2Z2kPfjb9q/eBKpo18Hg37vldPhI3sq51YSGrqrrOC3IfyprO/6AOyRgHOQOP9rxmbjgosCfz8vjQ7mnbq+TtMG+/jItJi8cDGKPggJFDCHKKrYtREQEh01ZmHKVFGfhKVPyAF4uFglMk65wrWT5T/AwX5rW48TC87NGc5/a/avs93J4oKtNsELWBtAj49n7T1Dbc/T79ZiWNHcxv5eYILf809jM8yqqxrSSCOkRqnD1tqXGTn+mVP0u1yZySfUIOuXnCzi1H0LIkcorqqaNqA5b7HO8qhPBiYoMGIEJlprVkT0N5O4NfhkIuZrhAIYzuAj6EIBNx3bjpmzKrMQzDf66fky5fwnQtIdNYiP0w6rjBe/j+THRi+AuktFFC5UmI5SDeAJjLZ6hctFyMEoSRNhbvFTMgFLCq36NDNsrT0JnECFU0Jg844A9zrcD+kVkDFyiJ8fVsaNP4EPPg9f6LADHBxrggGVhoV2fzWkykmEvz9zQhzhXDuqVHOXmtnQ8stdHFa3rYWOCtrKSTzqaV/xcqPIuvGg/mbFP4qvr7hsQpKvnX0POlF2WFeudHUBjEarE/0nGG38H4I+Iy4awFDD80yPWXEWf3HemEzv2FlqAkPyRR5js8eRYGEeH9zyvFWYR2obgX3SOD/Wkk6BNRbX0djr6rUzVyVi0NAMNREuGd/O6f4i4yN3twohfcVlIVQtHQWCCc6ZkqTez74hRPFlx/d+qQFhVwXu8S7+BE43x8Rlu7bMRiic+HRRMeXwGK9u+LV/XVlZuoOD6GI9MMlWzvGbGbth1Iwipo/be29KitcRw7nz9XkH/yZcvNHZRivoO2ZkTcdhs9zg4JfftXZxT/jA1GE0YhDVSUzlgs6MGJplx+jCKCw8X+iVLEbjwvwRpP5Jdn0d+S02MAZtRA2/MWQGWKtcHTjwmm/FPYOVn7FAchYJNlEM511IOliFLSAxkI4Rij8oV6s8IsPNzm3arMDvqxF4CJzPMhto24MajiVY3EGIqp2NUBZ3wkdXb7yShjGYXIOCg8S1WnjJpLwal6Us6EfrOVzbhFCptqOuBXPLK+8/B/Jl2d7fA7Aaz7HZdr9+BFpBe2GvHFytz5H3X4ul5AMppqvE4RifNYjmlxHMIJPgtfyhidpS+KnqH2aaunBZt+sJ9CqXJvCzjk7OW0+I4I3ipI4G0atTzfcYogYKGBxE9s711uxsZ8CamCfyJF8xD3ztBXNXY8a1j940v3KJpaQ3Zo7R1R5UNstlkctWloR23LaXfD3AHTBNrGayGc73Z1Yqgkq2F1Fkl39xe2Y6yQV/Os6xbXrcarU5TfqY3GubvrE/H6UtQ0QYY/DUtwVh2Rbwf4sAOL4QKEaM+tboE8sZmGVOyA1wEIcvR3Qt2r431hxePqKlApohuNuBd9cOA0iotx9Gb7LbLbiVfdwSvQqA5KtlJUDGL5PAnUubZT0QWbuNkkLk4Awf197G0xSjpXgZchG+CeZLIJ5CR8ca28/Nf,iv:dPqR9GVdbg5oHcf6N9j+3Gj0yhGiG2seRBPmeU/nQn4=,tag:lgaGdr7nWz2IMkHcEaImhA==,type:str]
    mosquitto:
        password:
            homeassistant: ENC[AES256_GCM,data:JRSJ+wAbCSOiQz9C/Yq3xJm1k0jyIytayIN8f0r5yAgQ638pKxggsL8CBwztuybG83hmsHEWYhUBVoF9p5CVt1U/JtC0VOHvYhd3CYczkV5LUVjtec1WRVcZf4kKRtaOE85qU6Caw/JYPSn1gUuKAg==,iv:Jc4Em/BORdlfkq/4sMa6dJbhhyfgxKzUJQTp6j8WX/8=,tag:RaqW9UExYXT1ohXJjkTl2Q==,type:str]
            nodered: ENC[AES256_GCM,data:F4H66ievdPj263R3JkVWYyZCJSuZwse7ZdM+3ltE0vEEtaz9ZLPPOlr2/dJMUJbjDUO5wbPJz2hWjbuc9FUbMajq3LhWG5AJUjvoBYhByQ70QvCaNc6ZytA4EaBsvP+kLsW2+rDFrtwshIwWEQqZGw==,iv:mJzTD5MbGO7fRZH7SAPv1AWy12f/fN/+yhIssxWcIb8=,tag:Mx8fpYBRABOt7ynSrgOsFQ==,type:str]
            zigbee2mqtt: ENC[AES256_GCM,data:TJfXuKyrSzoJx4wx4fmW8gKd+Z+njU2SO90dOdN70XQN13CmPCB/LTj2Yo0Qi1CJEAOnI7Lz/4INtDEEYn840az6M+7zOWQHMppvzTf5268JLzkd4mp7phB1Llbp5NHMIb/WcEhnXfUurOstNVS+FQ==,iv:ts0ewrDJgJjPU1w1zsU7cg+r8LHc5ajjCMdsMh2c6xo=,tag:MM2jPvVcCI0NeB4e+yaopw==,type:str]
    zigbee2mqtt:
        password: ENC[AES256_GCM,data:C7iB4A/KG/nsWFQ9GwfoPg==,iv:1b0DNz1A+rhOBzR+2rDXNioXQ4hTObE+yLOYF8TaNM8=,tag:BV+T3Ma3lRTwllYoiJiojw==,type:str]
        network_key:
            - ENC[AES256_GCM,data:Otb/QOJMSEz8pfv1dxpt6hHtuE2k1R0HqjkB08POAWN6X/LY01MwgJgeAEOCaaxmaYajou5dbw==,iv:60BkEzAB7+rpjvG/KvrjRbnZpDvVIuAWraHkg4O9ZQI=,tag:A52hxZ+ElZ+xJ+4z9Rxl6Q==,type:str]
        devices:
            "0x00124b0024c07db9":
                friendly_name: ENC[AES256_GCM,data:GPpDL0v9OqUNL9QM+x2TS7A=,iv:NXQQKUwoEkaU9Lq/ZzLkzu9InqFr+dXZ3sNTxgCo8ZY=,tag:o9bvQ0miwVIO4akhAIavdw==,type:str]
            "0x00158d00054d6a2e":
                friendly_name: ENC[AES256_GCM,data:BTNvJ5G3rsan0WCqjVeGfRw=,iv:uDrqyTagYOmeXliVGhIHz7zrIYSyvFVl81vfkJHX0xY=,tag:7b1U4to5FNtVUvdA4rMqtA==,type:str]
            "0x00158d0006d6a9a7":
                friendly_name: ENC[AES256_GCM,data:1ItrroXqY5nte5JEb+NZN+U=,iv:Y6pAFTPoAe0NF6esXm/Ow9akBdvCQJQo1CgskBWMwEE=,tag:DRrajbg3rD6Wo6jzEq7Cvw==,type:str]
            "0x00158d0006e3bb15":
                friendly_name: ENC[AES256_GCM,data:RRBTJNh0eVM39Y4myL9q,iv:PTM3SSEgAQZunr30rW1oXdfBHLhM0C2vPqI1Z5RE4Rk=,tag:XsF/+YDyb6uDSlV/7VmUHg==,type:str]
            "0x00158d000323c90c":
                friendly_name: ENC[AES256_GCM,data:AL3n5ffTVNM3kOzZnxw=,iv:tvdLWSAdFu8RvUAbfxSt06UdqXEDnjPzdk6ifoeZ+hE=,tag:1Mz15falN+qrmuzpwfbxyw==,type:str]
            "0x000d6ffffed187c9":
                friendly_name: ENC[AES256_GCM,data:zAM7FHbLM2S/0A==,iv:7Vy7XsXCIPMU450K+ERfsNKGtdkTtQK/2ArY8ayBPF4=,tag:suOuFD1/TCM/A7TYZ2GCIA==,type:str]
            "0x00158d00034d84a7":
                friendly_name: ENC[AES256_GCM,data:SW34gOXhPEgqGw==,iv:cynK37970NJ/JmsWs33be8Wyk7iwHypkwnR6TjQStFk=,tag:h7vXswXwQRKJ6+UOT+DM8w==,type:str]
            "0x00158d0001e88509":
                friendly_name: ENC[AES256_GCM,data:1IWRrpbNgJGKdTh7jWE=,iv:7eSRhRVJnHbiPusN02c7S9N32q/OAiPZ9MojskA0HqY=,tag:SPHTHedKk90xdpJYpWP72w==,type:str]
            "0x00158d0005a9e9c5":
                friendly_name: ENC[AES256_GCM,data:Qgm3MOfbznflOHlMdcI=,iv:UrgXlWJ3Xkt5iFIh9/AN9jpAIvPn2+T8B8EVrJkY3Yg=,tag:5Hqq8mKRCaY0HFpCagMArw==,type:str]
            "0x00158d000227a714":
                friendly_name: ENC[AES256_GCM,data:0H74DmVJbzGsXnEe/wv4TKtPmqTh,iv:GZVynd4cgSVOweQFoQ54kzFWBtHShgnXwDXPXvO+Fac=,tag:Gl53FDjXVG1qXtRlz9rVog==,type:str]
            "0x000d6ffffed18f67":
                friendly_name: ENC[AES256_GCM,data:ZUcGQZxFLor48aVR,iv:ZNqLHB7s/IJXkhrY569JOAhIfzdeUdYbURwTVBIuaZA=,tag:U4W1+zWEjr7afY4UAp0hHQ==,type:str]
            "0x000d6ffffe2a54ad":
                friendly_name: ENC[AES256_GCM,data:ykWtRHLKW6+fS9w=,iv:dapC1K3VWPTNt4HKY3d4xV+V367x4H0WCJ3VBlAe8Ac=,tag:eYpTCVnCuOuBiu8HAd971Q==,type:str]
                legacy: ENC[AES256_GCM,data:aX3xpCA=,iv:LQgKPjRQaFcilv80GSrL9Z7F0R5jN7fvpo3BxLK5tq8=,tag:Cyc3yrWS3DM1UVFdQb1shg==,type:bool]
                simulated_brightness: {}
            "0x00158d000353ea1e":
                friendly_name: ENC[AES256_GCM,data:IVTmm1dWmQBx5sNP,iv:xy7w4aIJuYZPRtwWxuoSwCMwRb7bJeUjQxQUx+3H1uM=,tag:bZfsIan7/3rqhG0La+jJvQ==,type:str]
            "0x00158d0006d689f0":
                friendly_name: ENC[AES256_GCM,data:Mmraje2VSIta2iLcyz2OAr/WlC0=,iv:01ICTAKxobd0aFwHwLpzhTz6HgT6Co/Vyy/hzpp5wA0=,tag:xGXIn9DZE4nOYVmzQlhzrA==,type:str]
            "0x00158d00056bb978":
                friendly_name: ENC[AES256_GCM,data:3ezMOg2gNGJH7lqh,iv:3gRvYC9D4XAKG5X49U3hrVO8db4ivf6iW/JAbZptL7w=,tag:EVR+GM8TkgpwIzM7YV0spQ==,type:str]
            "0x00158d00059531ef":
                friendly_name: ENC[AES256_GCM,data:c8hHQrQElKZmaN5bvA==,iv:Vz2Uk9/3M0Egd4ebEpWSRlmpqwPeAAAifcdBMjBSlDo=,tag:jvP3cXR3gpAQSH+hdLYREQ==,type:str]
            "0x00158d0002b5976a":
                friendly_name: ENC[AES256_GCM,data:f8Kp6C2fePY07v0DdQ==,iv:X3ZsEkBf97V92A50Q6U1sFO8V2dgYZTLC3zVJxOlCjg=,tag:UieKYO+MsAmwvICDt1xTUQ==,type:str]
            "0x00158d0002b5a49e":
                friendly_name: ENC[AES256_GCM,data:mHoqiM5V//SWeh+dyY4=,iv:O8DCMgKYiiLEFvqmh9pkXbXhJhwUOj4HYhElfHBz4Vs=,tag:OtruBFudet+HtqJZQvf6jA==,type:str]
            "0x00158d0002b6fda5":
                friendly_name: ENC[AES256_GCM,data:fYe9GGph3dqZU99/TA==,iv:HSGqV4i7HCujhpqR/wQA+0TP0M8J+vLThifYkECwnss=,tag:sJBdFhrMjm1nwnFyiywkOA==,type:str]
            "0xd0cf5efffeebfac7":
                friendly_name: ENC[AES256_GCM,data:9TkpLzoetZSXZLmjNiZVcg==,iv:B68/JrTd/50WgMjqWBw9kVRoOwhtCNwQ/5bPNCbbQeg=,tag:caGRl93EfdBsz2p76ZzoMg==,type:str]
            "0x00158d0006d666a0":
                friendly_name: ENC[AES256_GCM,data:1HVNjA6oSq3BiEQ=,iv:hmutUuQo3BBZZbEb4D4v8viIX7znxDxfVTSzAqUUMOE=,tag:NReg+yGFnoCdfVzc/KBlxA==,type:str]
            "0x00158d0001e8877a":
                friendly_name: ENC[AES256_GCM,data:OsWvQ2LrEjKzMCw=,iv:6e6sSmWeb1B2m5opl7G+sSTC6soHBe3aYBIa7tYcNlU=,tag:1smrndTa9C4/vSbe1vRFvw==,type:str]
            "0x00124b0024c2555c":
                friendly_name: ENC[AES256_GCM,data:5+15SAJSPg81h7VaNkzYdg==,iv:1pCT6TieP/5uvV9714lZjmJZ13LuiR3eQENobdUWM94=,tag:ff3K57K0AWnNJthkkFulVA==,type:str]
            "0x00124b0024c10e65":
                friendly_name: ENC[AES256_GCM,data:xm/OIVSN++xx7dCO6DfLDxpc,iv:HVJhU5+SiEUq+zx51VzC2Mey+RM3oUfnHQ6BB/VWaXA=,tag:C3xeEnSK7A/hkuhKP0XUwQ==,type:str]
            "0x00124b0024c10d59":
                friendly_name: ENC[AES256_GCM,data:tX1shl9e,iv:Pc75agiEqVGiYlmu7Rh+/Wh7+w1Uenb9xLKEPjouUbY=,tag:Z0wsbS+FPA9T2TA/4jYpBw==,type:str]
            "0x086bd7fffe035cc7":
                friendly_name: ENC[AES256_GCM,data:cUYDlYrslNovyVkOdQZJsMNl,iv:ykgEyf98zLcgND6HEIPC4p0i1scxlEBCaaVs+kqhcR8=,tag:4ivtt63JXs+KMw+x8N9Jlw==,type:str]
            "0x000b3cfffefadfd2":
                friendly_name: ENC[AES256_GCM,data:W50NPmi0EX7az+bL/umzZWgdmw==,iv:kL9ydIYmq3rcHtKsgPbhIOI1WgjOKwmJoNrktxKhO+s=,tag:Pki7i33aMR3bbzUvBJi9JA==,type:str]
            "0x00158d000177f1e7":
                friendly_name: ENC[AES256_GCM,data:km9H1cQO3muectSguvWE8C4+,iv:emyZIlK5Mr6b7jKxEyi6RyDguuX7pc7FcQy+/b6OLJc=,tag:od9HQahDUVyifkOBs3eZNA==,type:str]
            "0x000d6ffffee46026":
                friendly_name: ENC[AES256_GCM,data:IRMGOoxpqeavuWhhTew4/Zlf,iv:8qGrNKtLScv/DuFfvGsrKUFz3gB8XJ9ah9bFygj/9X0=,tag:EHMs7rL3ShywGHLoRK3KiQ==,type:str]
            "0x00124b001f69bcc7":
                friendly_name: ENC[AES256_GCM,data:LJCMGgcTMNRNHJW6B5o=,iv:q5ZkocF/ktcTxE6M6UQCtkMU7Vykt+HSPHJAhJHFK7M=,tag:Kv8BukqgwyWch1sQo6uXNg==,type:str]
                transition: ENC[AES256_GCM,data:Iw==,iv:b0Y7VxEc2nUntasuvselTMe2s7TCC3oh/UkscDRLbu8=,tag:zSGLqWd9x5YUOikOiNomcQ==,type:int]
            "0x00124b0024c07d42":
                friendly_name: ENC[AES256_GCM,data:UVb9CUWAHeKa23Y4X4WcPCfJfgU=,iv:dbQT/0LyAwDRY8nCZn2MHGQc4IgIFsaouRBW5LMyyQI=,tag:F9o5T7m5iIon9GS8aY571Q==,type:str]
            "0xa4c1384734784c55":
                friendly_name: ENC[AES256_GCM,data:6u6hv+iVD9WSjhwmE0nKs8tb,iv:FRHnQjHpPXR5KcYqiScV+KvMOjjq6cD3RIEKqCZWn6w=,tag:jH1VEouHQ1opFebs9MJ5Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15hk7pe2gnh3h7cmnv4sf0gfp4p5gwul66nxtm4a22xhltam4du5s0zq8rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUDQxbDk2Z1BMRUVQSXFF
            cXNnWi82cjIzY1FXcEV1MVJBOGh5dUw4WWhJCjJhaG91Wm95czVpeUdEbkxKdlpu
            Y0ZPUHp0M25CVEx0cVhzT0lnMHdYajAKLS0tIGoxZitLMm1yR2xPRUJCcVYrS1ZM
            MUcwMmRENFBTL0FTM1VDc2xnMWt1ckEKboTP2ZtQptR7ixVooSp3WvmfI1wDG2FU
            LyDdZDxtJZT41ryisyZDeam+3rLbhtUGCHd+S99Vq9li8R4963HvPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezktueyxlkm6qg583jrjngecw662w4k480d5kj3cgh070uyz6f6qdwxx3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTEhQQmVKZnFwM0F2RUFo
            Wm4xS3BtZ0RSdEZLL2NkSWxxeHJVUEtBVmpVCnhxaHRDVTNIRnlhVzFWb0J3TTFB
            czlHOW9DQm5VZ0ZnQ1dRaUZQSDdpMUEKLS0tIDhvN0gxU1U4aDViaERaaWhmYWIz
            NGNIMmw3OVBtaVZNcU43QkdGcTF0MUEKo2A9WgGHFiZy6cFVmRG3N8GoOOVrnerK
            n2so0enoKP+lKWxSCqYnfv/TRLZfuQuLfEYOgLyU87AQ7Q5KrvN4+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m3h9cfyuqdapfuw3dydx90qwcdpmtqts9yxp7gljd808595fzdxs0ea4t8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdXZZOWp0dnBjeTZZUTRs
            SmlRQWh4WmUxa042NnJFa01ITEZ6Z2E4eDI0CjdBL1pvVVQ2WjI2WkF1R2NMbWdK
            RUtiYXZVZG51MkdTOU9IYld6Qm5NOGsKLS0tIFBnSWFwdnJuSjYxNFVTSGJWTGN1
            YjVsQURMWnY3L1RGdy9aYUdTMVpGNVEKF8Qw79mxSuEMkqPQxKE8RnGRZVEb4rgQ
            Zvp7DqmfUaVEi0vJrsruAyM/lNVigBwn5LZHcgfvAS5J2aUD33X0LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyrcctsjpxqd732emuhuyrp2nn3f8ejzxmanyt9pgwyzs46kgaesd08muf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSU5uU09wd1ZFd0hMcjRE
            MWF6ZkpOV2pEVEt0d2t6Yk5mQmxxWUl3TVhVCnNGNVMyNlZrYzFJTHNyQ0NKd3Vp
            VVNxNkVSRTdXOG54ZHp0NDJuTEI2OVkKLS0tIC81Z2QzblQvK1FlZ3hqUW9scm4z
            VzJVMitXaFZUalBOZGs5VjNwQkZZMU0K96qCDpAV1Ks7kXFgifWCbMNAXQJxeOfi
            qrCcyVwH++Z5Qd2wS915r60HW5yAPXHYixWLdBSibk3TYrYS9YrEqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T12:37:59Z"
    mac: ENC[AES256_GCM,data:5IkcHtasWfUCJV8921/rnTuTF/dn5PMf+fmu6RiAEaHUxyK4x6uvFnw0J+MuTb2zTVLFSpkaDwIznxepxTYp2YG54R2sJmT691dRfm/FAR5qv/0DtU2wgY+9nbtk5QeJsdnLzP2+zzaS1KdWkzea2l2V1dSRc/Wlo9Mq2P3ZDs0=,iv:UlT/PKs+Wij2Vx5bzUG0tuxf3TcYkzGLBafv8lQp+i0=,tag:2MZM3chEFp9N2AbNUEDESA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
