---
logo: "\uf313" # Nixos logo

font:
  text:
    family: "Hack Nerd Font"
    size: 18
  icon:
    family: "Material Design Icons"
    size: 22
  weather:
    family: "Weather Icons"
    size: 22
  logo:
    family: "font-logos"
    size: 22

bar:
  opacity: 0.8
  top:
    height: 40
    margin:
      - 8
      - 8
      - 0
      - 8
  bottom:
    height: 40
    margin:
      - 0
      - 8
      - 8
      - 8

base16_scheme:
  base00: "2E3440"
  base01: "3B4252"
  base02: "434C5E"
  base03: "4C566A"
  base04: "D8DEE9"
  base05: "E5E9F0"
  base06: "ECEFF4"
  base07: "8FBCBB"
  base08: "BF616A"
  base09: "D08770"
  base0A: "EBCB8B"
  base0B: "A3BE8C"
  base0C: "88C0D0"
  base0D: "81A1C1"
  base0E: "B48EAD"
  base0F: "5E81AC"
# base16_scheme_name: nord

layout:
  margin: 9
  border_width: 4
  border_focus: "base08"

widget:
  foreground: "base04"
  background: "panel_bg"

powerline_separator:
  - "forward_slash"
  - "back_slash"
  # - "arrow_right"
  # - "arrow_left"

powerline_color_repeat:
  function: cycle
  indices:
    - 0
    - 3

# powerline_color_repeat: false
